##---------------------------------------------------------------------##
# Simulation parameters
total_time: 0
current_time: 0
use_real_time: False
time_step: 1.0
headless: True
dynamic: False
adversary_visible_range: 10 # in km
number_adversaries: 20
number_targets: 1
num_agents: 3
num_episodes: 1000

##---------------------------------------------------------------------##
experiment:
  type: []
  map_to_use: 'chicago'
  record_video: False
  log_states: False
  detailed_model: True
  node_attributes:  ['x','y']
  edge_attributes:  ['length']
  max_timesteps: 10000
  adversary_reward_multipler: 10

##---------------------------------------------------------------------##
# Paths
urdf_data_path: 'shasta/assets/'
